### PR TITLE
Added unzipWith for pull vectors

### PR DESCRIPTION
**Pull request by kmate**
I would like to use it in my Blowfish example, but it could be handy in other several cases.

### CODE REVIEW

**Comment by emilaxelsson** [comment]
I don't really like this function, because it gives a false impression that the function `(ab -> (a, b))` is used once for each `ab`, when in fact, it is used once for each `a` and once for each `b`. So `unzipWith f v` is really just `(fmap (fst.f) v, fmap (snd.f) v)`. Even if the latter is a bit longer, I think it makes it more clear what's happening operationally. What do you think?

**Comment by kmate** [comment]
It's right, I had the same impression. I just wanted to be short in my paper, and it would be easier to say that this is provided by Feldspar, then omit the details :)

**Comment by kmate** [comment]
But... As `f` must be pure (and this thing is lazy) the multiple usage does not really matter, right? So what is the danger behind thinking that it will be used once, if `f` is pure?

**Comment by emilaxelsson** [comment]
There's no semantic danger, but my expectations on a function

```haskell
unzipWith :: Pully vec ab => (ab -> (a, b)) -> vec -> (Pull a, Pull b)
```

are that I get sharing of the calls to the function `ab -> (a,b)`. The absence of functions like `unzipWith` gives me the useful information that there is no general way to get sharing between two pull vectors (without writing to memory).

Sorry if this seems like picking on details. But we have tried quite hard to make the vector library (in previous incarnations) so that it should be easy to reason about the code you get. This means that if you want to do something potentially inefficient such as writing to memory or duplicating a vector, you have to do this manually. In that sense it's good that the library forces me to write

```haskell
(fmap (fst.f) v, fmap (snd.f) v)
```

so that I see the duplication.

**Comment by kmate** [comment]
Ok, I accept it, it is completely understandable.

**Comment by emilaxelsson** [comment]
Could you perhaps define

```haskell
unzipWith :: Pully vec ab => (ab -> (a, b)) -> vec -> (Pull a, Pull b)
unzipWith f v = (fmap (fst.f) v, fmap (snd.f) v)
```

in the paper?. Then you don't have to explain the internals of pull vectors.

**Comment by kmate** [comment]
Maybe I won't have this definition, just inline right hand side, summarize the above thoughts in a sentence, then I really don't need to speak about `Pully` etc. Thanks anyway!

**Comment by kmate** [comment]
Just for completeness. The above type does not work with the given right hand side, it requires `vec ~ Pull ab`. However, this more general type works, and also covers the case I need, as Pull vectors are Functors:
~~~~
unzipWith :: Functor f => (ab -> (a, b)) -> f ab -> (f a, f b)
~~~~

**Comment by emilaxelsson** [comment]
Good point!

**Comment by emilaxelsson** [comment]
I just saw that `unzip` is in the library (once added by me) :)

I've removed it now.

**Comment by kmate** [comment]
I think I copied most of the code for `unzipWith` from there :)

**Pull request closed without merging**
