### PR TITLE
Casting the result of `round` to the appropriate integral type

### PR DESCRIPTION
**Pull request by kmate**
For details, see the new comment block in the code.

### CODE REVIEW

**Comment by emilaxelsson** [comment]
Why isn't the cast needed for 64-bit integers?

**Comment by kmate** [comment]
As `roundl` already returns a `long`, and not a `double` as `round`, it is not needed.

**Comment by kmate** [comment]
I wanted to write `lround` of course, but it does not matter, both return `long`.

**Comment by emilaxelsson** [comment]
@kmate If you agree about using `lround` always could you change to that?

**Comment by kmate** [comment]
If I change it to use `lround` in all cases, the cast will remain necessary I think. Because it will return `long int` all the time, and maybe the resulting Feldspar integral was a `Word8` mapped to `uint8_t`. Here the C compiler will give an error - as it is a casting to a narrower type.

So the solution could be the following: do not switch on the size, but always use `lround` and apply cast. Do you agree?

**Comment by emwap** [comment]
Yes. Use the appropriate `lround*` function based on the source type. Cast to the correct integral type. It would be nice to only cast when necessary, but purely cosmetic. 

I guess a cast-helper function could handle it for this case and several others.

**Comment by kmate** [comment]
That seems to be a better solution. Also, we can loose the constraints on the result type, it must not be an integral (now there is no way to round a double and then keep the result as a double??).

The casting helper would also be helpful to have but I think I will not do it in this round, as it needs a lot more work... I wanted to fix this only because it caused problems in my Zeldspar example application.

**Comment by emwap** [comment]
The `lround*` family returns integrals.

`double      round( double arg );` works for doubles and `roundf` handles floats.

**Comment by kmate** [comment]
Both `lround` and `round` have type-generic macros in C99 <tgmath.h>. So when the output is integral type, I will use `lround`, and `round` otherwise.

**Comment by emwap** [comment]
:+1:

**Comment by kmate** [comment]
So, here it is... I also made a utility called `compCastExp` to avoid duplication of the casting CExp + its type compilation. I left the unnecessary casts in place for now... Well it is not perfect, as you can round a complex in Feldspar, but it will be unable to generate code from it. Do you have any better idea than using `Num` as return type constraint?

**Comment by emilaxelsson** [comment]
Thanks!

The result of `round` can be cast to complex in C, so we should be able to support that. But I can take care of that.

**Pull request merged**
